

export const categoryConstants={

        GET_ALL_CATEGORY_REQUEST:"GET_ALL_CATEGORY_REQUEST",
        GET_ALL_CATEGORY_SUCCESS:" GET_ALL_CATEGORY_SUCCESS",
        GET_ALL_CATEGORY_FAILURE:"GET_ALL_CATEGORY_FAILURE",
        ADD_NEW_CATEGORY_REQUEST:"ADD_NEW_CATEGORY_REQUEST",
        ADD_NEW_CATEGORY_SUCCESS:" ADD_NEW_CATEGORY_SUCCESS",
        ADD_NEW_CATEGORY_FAILURE:"ADD_NEW_CATEGORY_FAILURE"
    
}

export const productConstants={
    GET_PRODUCTS_BY_SLUG:"GET_PRODUCTS_BY_SLUG",
    GET_RANDOM_PRODUCT_REQUEST:"GET_RANDOM_PRODUCT_REQUEST",
    GET_RANDOM_PRODUCT_SUCCESS:"GET_RANDOM_PRODUCT_SUCCESS",
    GET_RANDOM_PRODUCT_FAILURE:"GET_RANDOM_PRODUCT_FAILURE",
}

export const cartConstant={
    GET_CART_DATA_SUCCESS:"GET_CART_DATA_SUCCESS",
    ADD_CART_DATA_SUCCESS:"ADD_CART_DATA_SUCCESS",
}
export const orderConstant={
    GET_ORDER_DATA_SUCCESS:"GET_ORDER_DATA_SUCCESS",
    ADD_ORDER_DATA_SUCCESS:"ADD_ORDER_DATA_SUCCESS",
    DELETE_ORDER_DATA_SUCCESS:"DELETE_ORDER_DATA_SUCCESS"
}
export const authConstants={

    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_FAILURE:"LOGIN_FAILUR",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGOUT_REQUEST:"LOGOUT_REQUEST",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAILURE:"LOGOUT_FAILURE"
}
